backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "feed"
    label: "Feed"
    folder: "feed"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "{{media_folder}}/feed"
    public_folder: "{{public_folder}}/feed"
    format: "frontmatter"
    extension: "md"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Text"
        name: "text"
        widget: "markdown"
        required: true
      - label: "Date"
        name: "date"
        widget: "datetime"
        required: true
      - label: "Main Image"
        name: "image"
        widget: "image"
        required: true
      - label: "Category"
        name: "category"
        widget: "string"
        required: true
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Enable Share Button"
        name: "enable_share"
        widget: "boolean"
        default: true
      - label: "Enable Copy Link Button"
        name: "enable_copy_link"
        widget: "boolean"
        default: true

# Note: Admin index.html will be served at /admin/index.html to load Netlify CMS UI
